apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: code-server
  namespace: code-server
spec:
  interval: 60m
  chart:
    spec:
      chart: ./ci/helm-chart
      version: '3.2.0'
      sourceRef:
        kind: GitRepository
        name: code-server
        namespace: flux-system
  values:
    extraArgs:
      - --auth 
      - none