apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: db
  labels:
    app: postgres
data:
  POSTGRES_DB: ${SECRET_POSTGRES_DB}
  POSTGRES_USER: ${SECRET_POSTGRES_USER}
  POSTGRES_PASSWORD: ${SECRET_POSTGRES_PASSWORD}
  BACKUP_PHRASE: ${SECRET_BACKUP_PHRASE}
  PGDATA: /var/lib/postgresql/data/db
            