apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: first-pool
  namespace: networking
spec:
  addresses:
  - 192.168.50.247-192.168.50.254
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: first-pool-l2-advertisement
  namespace: networking
spec:
ipAddressPools:
- first-pool