apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rancher
  namespace: cattle-system
spec:
  interval: 60m
  chart:
    spec:
      chart: rancher
      version: '2.7.1'
      sourceRef:
        kind: HelmRepository
        name: rancher
        namespace: flux-system
  values:
    hostname: rancher.local.danielvignoles.com
    bootstrapPassword: ${SECRET_RANCHER_BOOTSTRAP_PASSWORD}
    tls: external